defaults:
  - override hydra/job_logging: default
  - override hydra/launcher: basic


wandb:
  project: deepmimic
  run_name: SACHFoot_ProsRight_Rep2Seed0_Horizon2000_MimTorsoHandsJointRootQPos12QVel06_LatRange05Coeff01_ActPenSquare002_2BoxesNew_solref_900_300_KN-120_5_HP-30_35_AnkL-20_20_AnkR-10_10_AnkStiffL900_Gas_SlackRange002_SocketTySlack_ObsPosOriSocketTalus_RandPosOriSocketTalus_LaPreStiffDamp_BothSideToeSameStiffDamp_NoSubTal
experiment:
  task_factory:
    name: ImitationFactory
    params:
      default_dataset_conf:
        task: walk
  env_params:
    env_name: MjxSkeletonMuscleProsthesis
    prosthesis_side: right_side
    prosthesis_type: transtibial
    prosthesis_subtype: SACH
    delete_joints: false
    remove_joint_names:
    - subtalar_angle
    tibia_socket_offset_z: 0
    tibia_socket_offset_x: 0
    tibia_socket_overlap: 0.2
    amputated_tibia_length: 0.2
    limit_knee_extension: true
    knee_extension_limit:
      ankle_angle_l:
      - -20
      - 20
      ankle_angle_r:
      - -10
      - 10
      hip_flexion_r:
      - -30
      - 35
      hip_flexion_l:
      - -30
      - 35
      knee_angle_r:
      - -120
      - 5
      knee_angle_l:
      - -120
      - 5
    contact_geom_type: 2boxes_new
    socket_ty_slack: true
    contact_solref:
    - -900
    - -300
    add_pos_ori_to_observation: true
    joint_stiffness:
      ankle_angle: 900
    reattach_muscle: true
    reattach_muscles_offset:
      med_gas:
      - 0
      - 0
      - 0
    use_2_box_per_foot: true
    headless: true
    disable_arms: false
    horizon: 2000
    goal_type: GoalTrajMimic
    goal_params:
      visualize_goal: true
    control_type: ${control_config.torque_control.control_type}
    control_params: ${control_config.torque_control.control_params}
    reward_type: MimicRewardVelArm
    reward_params:
      qpos_w_sum: 1.2
      qvel_w_sum: 0.6
      rpos_w_sum: 0.5
      rquat_w_sum: 0.3
      rvel_w_sum: 0.1
      action_coeff: 0.02
      lateral_range_coeff: 0.1
      lateral_pos_reward_range: 0.5
      sites_for_mimic:
      - upper_body_mimic
      - left_hand_mimic
      - right_hand_mimic
      joints_for_mimic:
      - root
  hidden_layers:
  - 512
  - 256
  lr: 0.0001
  num_envs: 2048
  num_steps: 200
  total_timesteps: 500000000.0
  result_dir: None
  checkpoint_num: 5
  update_epochs: 4
  proportion_env_reward: 0.0
  num_minibatches: 32
  gamma: 0.99
  gae_lambda: 0.95
  clip_eps: 0.2
  init_std: 0.2
  learnable_std: true
  ent_coef: 0.0
  vf_coef: 0.5
  max_grad_norm: 0.5
  activation: tanh
  anneal_lr: false
  weight_decay: 0.0
  normalize_env: true
  debug: false
  n_seeds: 1
  vmap_across_seeds: true
  validation:
    active: true
    num_steps: 100
    num_envs: 100
    num: 10
    quantities:
    - JointPosition
    - JointVelocity
    - RelSitePosition
    - RelSiteVelocity
    - RelSiteOrientation
    measures:
    - EuclideanDistance
    - DynamicTimeWarping
    - DiscreteFrechetDistance
    rel_site_names:
    - upper_body_mimic
    - left_hand_mimic
    - right_hand_mimic
control_config:
  torque_control:
    control_type: SkeletonMuscleControlFunction
    control_params: null
randomization_config:
  randomization_type: ProsthesisRandomizer
  randomization_params:
    randomize_prosthesis_dof_damping: false
    prosthesis_dof_damping_range:
      ankle_angle:
      - 2
      - 10
    randomize_prosthesis_joint_stiffness: false
    prosthesis_joint_stiffness_range:
      ankle_angle:
      - 50
      - 100
    randomize_prosthesis_body_position: true
    prosthesis_body_position_range:
      pylon_socket:
        x:
        - -0.02
        - 0.02
        z:
        - -0.02
        - 0.02
      talus:
        x:
        - -0.01
        - 0.01
        z:
        - -0.01
        - 0.01
    randomize_prosthesis_body_orientation: true
    prosthesis_body_orientation_range:
      pylon_socket:
        x:
        - -0.2
        - 0.2
        'y':
        - -0.3
        - 0.3
        z:
        - -0.2
        - 0.2
      talus:
        x:
        - -0.1
        - 0.1
        z:
        - -0.1
        - 0.1
    randomize_prosthesis_socket_joint: false
    socket_joint_range:
      socket_ty:
      - -0.25
      - 0.025
    adapt_tibia_socket_parameters: false
checkpoint_path: /media/calc_2/loco-mujoco_results/prosthesis_rand_save/outputs/2026-01-02/10-26-03/SavePPOJax_saved.pkl
